### ISSUE TITLE
Key events aren't being fired when the StructuredFilter is included in a custom component

### ISSUE THREAD

**Issue by ravsom** [joshcarr/react-structured-filter#11]
Key events like "Enter", "Backspace" and "Tab" don't fire the listeners. Ain't able to get a call on the update when any of those change for "textoptions" kind of option

**Comment by ravsom** [comment]
We figured out that we were registering some key events that conflicted with the StructuredFilter's key events and so the key down events were firing.

**Comment by joshcarr** [comment]
Ok, closing this issue.
