### ISSUE TITLE
getOptions redux?

### ISSUE THREAD

**Issue by mstruensee** [joshcarr/react-structured-filter#14]
is it possible to use to this:
function getOptions() {return ["MSFT", "AAPL", "GOOG"]}

via an api call using redux + store + reducer?

**Comment by joshcarr** [comment]
It could be possible. If you find a way and want to make a pull request to the documentation, please do!

**Comment by mstruensee** [comment]
Are you able to provide an example of it doing ajax without redux?

**Comment by mstruensee** [comment]
This will work as is currently with redux, but since it is an "ajax" call it does not pop up anything until it gets the response ... maybe default a box with a spinner would make it more clear that it is doing something.
