### ISSUE TITLE
[FEATURE]: Configurable operators

### ISSUE THREAD

**Issue by nickdeis** [joshcarr/react-structured-filter#9]
Hey, this seems to be the most active branch, so I'm submitting the idea I'm currently working on.
Basically, operators should be configurable by passing them in as a property.
These should be merged with the default operators (using object-assign, a dependency for React and ReactDOM).

Example  
```javascript
{
  "textoptions":["equals","does not equal"],
  "text":["like","not like","equals","does not equal","matches","does not match"]
}
```

**Comment by joshcarr** [comment]
This sounds like a great idea. Would love to review a pull request.
